---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: library-system
  labels:
    app: cart-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
      version: v1
  template:
    metadata:
      labels:
        app: cart-service
        version: v1
    spec:
      containers:
      - name: cart-service
        image: your-registry/cart-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: REDIS_ADDR
          value: "redis-central.default.svc.cluster.local:6379"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: library-system
  labels:
    app: cart-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: cart-service
